#!/usr/bin/python2

import random

n = random.randint(1, 10)
m = random.randint(1, 10)
k = random.randint(1, 20)

print '%d %d %d' % (n, m, k)

for _ in xrange(k):
  t = random.randint(1, 3)
  r = random.randint(1, n)
  c = random.randint(1, m)
  print '%d %d %d' % (t, r, c)